### ISSUE TITLE
(QGroundControl.exe:5684): GLib-GObject-CRITICAL **: 13:21:59.584: g_object_set: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by jorgitinlugo** [mavlink/qgroundcontrol#12189]
I am trying to compile my own version of QGroundControl. To do this, I followed the official QGroundControl tutorial and installed Qt 6.6.3. The thing is, when I try to build the code, I get the following error:

![image](https://github.com/user-attachments/assets/6f0ac11e-bc67-4c0b-8533-5213d8cf0c26)

I have correctly selected the Qt 6.6.3 MSVC2019 64-bit kit.

![image](https://github.com/user-attachments/assets/d5055c9b-09c0-44c3-afb4-6600a884d20e)

**Comment by HTRamsey** [comment]
rebase and try again now

**Comment by jorgitinlugo** [comment]
@HTRamsey rebase? Im very lost with all of this, if you can explain it to me...

**Comment by HTRamsey** [comment]
Actually sorry first make sure you have GStreamer 1.22 development and runtime installed. Then you can try to pull the latest change I just committed to this repo, but I think that's not your problem. It mostly just looks like gstreamer isn't installed.

**Comment by jorgitinlugo** [comment]
@HTRamsey Should i use master branch or Stable 4.0?

**Comment by HTRamsey** [comment]
Up to you. If you are using an old stable you should use QMake instead of CMake & gstreamer 1.18.6 instead of 1.22+.

**Comment by jorgitinlugo** [comment]
@HTRamsey I tried to add an image and when i run the code i get this error:

![image](https://github.com/user-attachments/assets/54c3fe84-e341-4e4e-b5ae-b7e670f99f7f)

i reverted the changes and now i still have the same problem, do you know what could be?

**Comment by jorgitinlugo** [comment]
I decided to reinstall the qground repository, when i tried to upload a new photo to qgcimages.qrc i get this error:

(QGroundControl.exe:5684): GLib-GObject-CRITICAL **: 13:21:59.584: g_object_set: assertion 'G_IS_OBJECT (object)' failed

Qground works but i dont see the new photo in my gui

**Comment by HTRamsey** [comment]
You can ignore the WaylandClient warning. did you look at the custom build stuff for more info on how to correctly add images?

**Comment by jorgitinlugo** [comment]
@HTRamsey Thank you for your help. The issue I had was related to the compilation process. It seems that making changes requiring compilation would cause it to fail, which is odd since the compilation should be dynamic, right? The process I followed was to delete the build folder and, instead of using Ninja to compile, I used Visual Studio with the following command in the terminal: 

`cmake -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug`

**Comment by HTRamsey** [comment]
Oh okay gotcha. Qt also provides a cmake script called qt-cmake that you can probably use instead of calling cmake directly, which is what I use in the CI workflows. Are you still having any issues now?
