### ISSUE TITLE
Daily Builds and 5.0 stable cannot slide the slider when executing the landing command.

### ISSUE THREAD

**Issue by mengchaoheng** [mavlink/qgroundcontrol#13260]
### Have you checked the latest release for fixes?

- [x] Yes, I’ve tested on the latest release

### Description

cannot slide the slider when executing the landing command.

### System Information

Daily Builds and 5.0 stable

**Comment by mengchaoheng** [comment]
px4 v1.16.0  is compatible with which version of QGC?

**Comment by HTRamsey** [comment]
Just the land command? That's very odd and I wasn't able to reproduce this. What is your platform?

**Comment by mengchaoheng** [comment]
macOS m1, both return and land. By the way, on apple m1 platform, app cannot open, this is a issue from 4.4.3 to 4.4.5.

**Comment by HTRamsey** [comment]
@DonLakeFlyer could you check this on your Mac?

Also we're aware of the Mac issue on 4.4 but it's unlikely it'll get fixed at this point

**Comment by DonLakeFlyer** [comment]
I tested with SITL and a multi-rotor and it worked fine for me. How are you sliding: mouse? trackpad? Does the spacebar slide work?

**Comment by DonLakeFlyer** [comment]
When you say "cannot slide the slider" what exactly do you mean:
* The slider won't physically slide in the UI? 
* Or when you confirm the confirmation itself doesn't work and say Land doesn't happen?
* The slider doesn't show up when you click the Land button

**Comment by mengchaoheng** [comment]
@DonLakeFlyer After sliding the slider and releasing it, the aircraft does not land and the slider falls at the end. I don't have this problem with other versions of QGC. I still don't know the reason, so I'm still using version v4.x.x.

**Comment by DonLakeFlyer** [comment]
Most likely same problem as #13325

**Comment by DonLakeFlyer** [comment]
@mengchaoheng Can you try latest daily build? I believe this had been fixed.

**Comment by mengchaoheng** [comment]
@DonLakeFlyer Now it works well.
