### ISSUE TITLE
The latest daily build doesn't work on Mac OS X 10.10.5 anymore

### ISSUE THREAD

**Issue by IeiuniumLux** [mavlink/qgroundcontrol#4974]
I donwloaded today's daily build and I got this message when I tried to launch it.  The last daily build I used from last week works fine.
<img width="419" alt="screen shot 2017-04-13 at 7 54 09 am" src="https://cloud.githubusercontent.com/assets/3729432/25010364/beef4030-201e-11e7-9c73-4062bde8c254.png">
<img width="982" alt="screen shot 2017-04-13 at 7 54 23 am" src="https://cloud.githubusercontent.com/assets/3729432/25010371/c632231c-201e-11e7-8dab-e403edcd9b30.png">

**Comment by dogmaphobic** [comment]
Installer issues? It's not finding the Qt libraries. Specifically, QtLocation.

**Comment by DonLakeFlyer** [comment]
Hm, thought I had fixed that. I'll look.

**Comment by IeiuniumLux** [comment]
Let me know if you want me to test/confirm the fix once you have a daily build available for it.

**Comment by DonLakeFlyer** [comment]
Usually means I pulled something out of the Qt 5.7 image up on S3 that I shouldn't have.

**Comment by DonLakeFlyer** [comment]
Fixed

**Comment by IeiuniumLux** [comment]
Is there a new daily-build or do you have wait until tomorrow?

**Comment by DonLakeFlyer** [comment]
New daily is posted.

**Comment by IeiuniumLux** [comment]
Unless there is a different url for the daily builds, then it still doesn't work.  I just downloaded it from here:
https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.dmg

**Comment by DonLakeFlyer** [comment]
Hmm, strange. It works fine on one of my machines but not on the other.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you have some quick time to look at this. The strange thing is that the QtLocation framework is in the package if you open it up? Not sure what is going wrong in there.

**Comment by DonLakeFlyer** [comment]
I thought that the travis s3 Qt tar was wrong. But looks like that wasn't it.

**Comment by DonLakeFlyer** [comment]
If I build locally using the same tarball it wll works fine. Hmm... A bit stumped at this point.

**Comment by DonLakeFlyer** [comment]
Ok, so I just tar'ed up a full regular 5.7 install. That didn't work either. Something strange going on with 5.7.1.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic I have no idea what is going on here with QtLocation. Seems to have broken with 5.7.1.

**Comment by dogmaphobic** [comment]
I downloaded the current daily and it booted fine. How do I reproduce this?

**Comment by DonLakeFlyer** [comment]
Which is kind of what I've been seeing as well. Sometimes it works and sometimes it doesn't. I change something, test it. It all works fine. Download it. It all works fine. Then someone reports it not work, I download again. And suddenly the same exact things doesnt' work.

**Comment by DonLakeFlyer** [comment]
And I just tried it again and it worked. WTF!

@IeiuniumLux Can you try?

**Comment by mhkabir** [comment]
@DonLakeFlyer works for me now.

**Comment by DonLakeFlyer** [comment]
Great thanks. Maybe it's fixed maybe it's not. Not srue what caused it in the first place and not sure why it went way. Fingers crossed.
